---
name: Geo-Coder-GoogleMaps
version: v0.3.1
author:
  - 'Arnaud DUPUIS <a.dupuis@nabladev.com>'
abstract: Google Maps Geocoding API
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  HTTP::Request: 0
  JSON::Syck: 0.07
  LWP::UserAgent: 0
  Test::More: 0
  URI: 0
  XML::LibXML: 1.6
configure_requires:
  Module::Build: 0.35
provides:
  Geo::Coder::GoogleMaps:
    file: lib/Geo/Coder/GoogleMaps.pm
    version: v0.3.1
  Geo::Coder::GoogleMaps::Location:
    file: lib/Geo/Coder/GoogleMaps/Location.pm
    version: v0.3.1
  Geo::Coder::GoogleMaps::Response:
    file: lib/Geo/Coder/GoogleMaps/Response.pm
    version: v0.3.1
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
