---
name: Geo-Coder-GoogleMaps
version: 0.1
author:
  - 'Arnaud DUPUIS <a.dupuis@nabladev.com>'
abstract: Google Maps Geocoding API
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  HTTP::Request: 0
  JSON::Syck: 0.07
  LWP::UserAgent: 0
  Test::More: 0
  URI: 0
  XML::LibXML: 1.6
provides:
  Geo::Coder::GoogleMaps:
    file: lib/Geo/Coder/GoogleMaps.pm
    version: 0.1
  Geo::Coder::GoogleMaps::Location:
    file: lib/Geo/Coder/GoogleMaps/Location.pm
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
